import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.suppliers': 'Suppliers',
    'nav.purchaseOrders': 'Purchase Orders',
    'nav.dispensations': 'Dispensations',
    'nav.medicationAvailability': 'Medication Availability',
    'nav.currentStock': 'Current Stock',
    'nav.dispensationTracking': 'Dispensation Tracking',
    'nav.inventory': 'Inventory',
    'nav.reports': 'Reports',
    'nav.users': 'Users',
    'nav.reconciliation': 'Reconciliation',
    
    // Common
    'common.welcome': 'Welcome',
    'common.signOut': 'Sign out',
    'common.language': 'Language',
    'common.english': 'English',
    'common.french': 'Français',
    'common.units': 'units',
    
    // App title
    'app.title': 'Hospital Pharmacy Management',
    
    // Dashboard
    'dashboard.subtitle': 'Overview of pharmaceutical inventory',
    'dashboard.recentMovements': 'Recent Movements',
    'dashboard.recentMovementsSubtitle': 'Latest inventory movements',
    'dashboard.loading': 'Loading...',
    'dashboard.totalItems': 'Total Items',
    'dashboard.totalItemsDesc': 'Active inventory',
    'dashboard.totalStock': 'Total Stock',
    'dashboard.totalStockDesc': 'Units in stock',
    'dashboard.recentMovementsTitle': 'Recent Movements',
    'dashboard.recentMovementsDesc': 'Last 10 movements',
    
    // Inventory
    'inventory.subtitle': 'Overview of inventory movements',
    'inventory.loading': 'Loading...',
    'inventory.error': 'Error loading inventory data',
    'inventory.totalItems': 'Total Items',
    'inventory.totalStock': 'Total Stock',
    'inventory.recentMovements': 'Recent Movements',
    'inventory.search': 'Search',
    'inventory.searchPlaceholder': 'Item name...',
    'inventory.movementType': 'Movement Type',
    'inventory.allTypes': 'All types',
    'inventory.startDate': 'Start Date',
    'inventory.endDate': 'End Date',
    'inventory.date': 'Date',
    'inventory.item': 'Item',
    'inventory.type': 'Type',
    'inventory.quantity': 'Quantity',
    'inventory.user': 'User',
    'inventory.notes': 'Notes',
    'inventory.noMovements': 'No inventory movements found with the selected criteria',
    'inventory.purchase': 'Purchase',
    'inventory.dispensation': 'Dispensation',
    'inventory.adjustment': 'Adjustment',
    'inventory.transfer': 'Transfer',
    'inventory.expired': 'Expired',
    'inventory.damaged': 'Damaged',
    'inventory.return': 'Return',
    'inventory.currentStock': 'Current Stock',
    'inventory.stockLevel': 'Stock Level',
    'inventory.form': 'Form',
    'inventory.expiryDate': 'Expiry Date',
    'inventory.description': 'Description',
    'inventory.noStock': 'No items in stock found',
    'inventory.lowStock': 'Low Stock',
    'inventory.outOfStock': 'Out of Stock',
    'inventory.inStock': 'In Stock',
    'inventory.sortBy': 'Sort By',
    'inventory.sortOrder': 'Sort Order',
    'inventory.ascending': 'Ascending',
    'inventory.descending': 'Descending',
    'inventory.form.capsule': 'Capsule',
    'inventory.form.tablet': 'Tablet',
    'inventory.form.eyeDrops': 'Eye Drops',
    'inventory.form.cream': 'Cream',
    'inventory.form.gel': 'Gel',
    'inventory.form.powder': 'Powder',
    
    // Item Modal
    'inventory.modal.addNewItem': 'Add New Item',
    'inventory.modal.editItem': 'Edit Item',
    'inventory.modal.name': 'Name',
    'inventory.modal.nameRequired': 'Name *',
    'inventory.modal.description': 'Description',
    'inventory.modal.form': 'Form',
    'inventory.modal.expiryDate': 'Expiry Date (MM-YYYY)',
    'inventory.modal.expiryDatePlaceholder': 'MM-YYYY',
    'inventory.modal.currentStock': 'Current Stock',
    'inventory.modal.initialStock': 'Initial Stock',
    'inventory.modal.initialQuantity': 'Initial Quantity',
    'inventory.modal.quantityHint': 'Set the initial quantity for this item',
    'inventory.modal.actions': 'Actions',
    'inventory.modal.cancel': 'Cancel',
    'inventory.modal.create': 'Create',
    'inventory.modal.update': 'Update',
    'inventory.modal.saving': 'Saving...',
    'inventory.modal.adjustHint': 'To adjust stock quantities, please use the reconciliation feature.',
    
    // Dispensation
    'dispensation.subtitle': 'History of inventory movements and dispensations',
    'dispensation.loading': 'Loading...',
    'dispensation.error': 'Error loading dispensation data',
    'dispensation.purchases': 'Purchases',
    'dispensation.dispensations': 'Dispensations',
    'dispensation.adjustments': 'Adjustments',
    'dispensation.losses': 'Losses',
    'dispensation.search': 'Search',
    'dispensation.searchPlaceholder': 'Item name...',
    'dispensation.movementType': 'Movement Type',
    'dispensation.allTypes': 'All types',
    'dispensation.dateFrom': 'Date From',
    'dispensation.dateTo': 'Date To',
    'dispensation.date': 'Date',
    'dispensation.item': 'Item',
    'dispensation.type': 'Type',
    'dispensation.quantity': 'Quantity',
    'dispensation.user': 'User',
    'dispensation.notes': 'Notes',
    'dispensation.noMovements': 'No dispensation movements found with the selected criteria',
    'dispensation.purchase': 'Purchase',
    'dispensation.dispensation': 'Dispensation',
    'dispensation.adjustment': 'Adjustment',
    'dispensation.transfer': 'Transfer',
    'dispensation.expired': 'Expired',
    'dispensation.damaged': 'Damaged',
    'dispensation.return': 'Return',
    
    // Dispensations
    'dispensations.subtitle': 'Record medication dispensations quickly and efficiently',
    'dispensations.loading': 'Loading...',
    'dispensations.error': 'Error loading dispensations data',
    'dispensations.recentPrescriptions': 'Recent Prescribed Medications',
    'dispensations.searchPlaceholder': 'Search medications...',
    'dispensations.selectMedication': 'Select Medication to Dispense',
    'dispensations.forms': 'forms',
    'dispensations.noMedications': 'No medications available for dispensing',
    'dispensations.dispenseMedication': 'Dispense Medication',
    'dispensations.form': 'Form',
    'dispensations.selectForm': 'Select Form',
    'dispensations.expiryDate': 'Expiry Date',
    'dispensations.selectExpiry': 'Select Expiry Date',
    'dispensations.quantity': 'Quantity',
    'dispensations.notes': 'Notes',
    'dispensations.notesPlaceholder': 'Additional notes (optional)',
    'dispensations.dispense': 'Add to Staging',
    'dispensations.dispensedSuccessfully': 'Medications dispensed successfully',
    'dispensations.errorDispensing': 'Error dispensing medications',
    'dispensations.stagingArea': 'Staging Area',
    'dispensations.stagingSubtitle': 'Review medications before dispensing',
    'dispensations.noStagedItems': 'No medications staged',
    'dispensations.totalItems': 'Total Items',
    'dispensations.totalQuantity': 'Total Quantity',
    'dispensations.confirmDispensation': 'Confirm Dispensation',
    'dispensations.noStagedMedications': 'No medications staged for dispensation',
    'dispensations.noExpiryDatesForForm': 'No expiry dates available for this form',
    'dispensations.clickToDispense': 'Click to dispense',
    
    // Common
    'common.optional': 'Optional',
    'common.cancel': 'Cancel',
    'common.saving': 'Saving...',
    
    // Users
    'users.subtitle': 'Manage user accounts and permissions',
    'users.comingSoon': 'User management coming soon...',
    'users.loading': 'Loading users...',
    'users.error': 'Error loading users',
    'users.addUser': 'Add User',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.username': 'Username',
    'users.password': 'Password',
    'users.firstName': 'First Name',
    'users.lastName': 'Last Name',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.actions': 'Actions',
    'users.save': 'Save',
    'users.cancel': 'Cancel',
    'users.confirmDelete': 'Are you sure you want to delete this user?',
    'users.userDeleted': 'User deleted successfully',
    'users.userUpdated': 'User updated successfully',
    'users.userCreated': 'User created successfully',
    'users.errorUpdating': 'Error updating user',
    'users.errorCreating': 'Error creating user',
    'users.errorDeleting': 'Error deleting user',
    'users.roleAdmin': 'Administrator',
    'users.rolePharmacist': 'Pharmacist',
    'users.roleTechnician': 'Technician',
    'users.statusActive': 'Active',
    'users.statusInactive': 'Inactive',
    'users.newPassword': 'New Password',
    'users.confirmPassword': 'Confirm Password',
    'users.passwordMismatch': 'Passwords do not match',
    'users.passwordRequired': 'Password is required',
    'users.passwordMinLength': 'Password must be at least 6 characters',
    'users.usernameRequired': 'Username is required',
    'users.firstNameRequired': 'First name is required',
    'users.lastNameRequired': 'Last name is required',
    'users.roleRequired': 'Role is required',
    'users.accessDenied': 'Access Denied',
    'users.noPermission': 'You do not have permission to access this page.',
    'users.userCreatedSuccess': 'User created successfully',
    'users.userUpdatedSuccess': 'User updated successfully',
    'users.userDeletedSuccess': 'User deleted successfully',
    'users.createError': 'Error creating user',
    'users.updateError': 'Error updating user',
    'users.deleteError': 'Error deleting user',
    'users.saving': 'Saving...',
    'users.deleting': 'Deleting...',
    'users.success': 'Success',
    'users.dismiss': 'Dismiss',
    'users.search': 'Search',
    'users.searchPlaceholder': 'Search by name or username...',
    'users.filterByRole': 'Filter by Role',
    'users.allRoles': 'All Roles',
    'users.clearFilters': 'Clear Filters',
    'users.previous': 'Previous',
    'users.next': 'Next',
    'users.showing': 'Showing',
    'users.to': 'to',
    'users.of': 'of',
    'users.results': 'results',
    
    // Login
    'login.title': 'Hospital Pharmacy Management',
    'login.subtitle': 'Sign in to your account',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.signIn': 'Sign in',
    'login.signingIn': 'Signing in...',
    'login.credentials': 'Default login credentials:',
    'login.usernameRequired': 'Username is required',
    'login.usernameMinLength': 'Username must be at least 3 characters',
    'login.passwordRequired': 'Password is required',
    'login.loginFailed': 'Login failed',
    'login.adminCredentials': 'Admin: admin / admin123',
    'login.pharmacistCredentials': 'Pharmacist: pharmacist / pharmacist123',
    'login.technicianCredentials': 'Technician: tech / tech123',
    
    // Reconciliation
    'reconciliation.title': 'Inventory Reconciliation',
    'reconciliation.subtitle': 'Reconcile actual medication quantities with system records',
    'reconciliation.totalItems': 'Total Items',
    'reconciliation.totalCurrentStock': 'Total Current Stock',
    'reconciliation.totalActualStock': 'Total Actual Stock',
    'reconciliation.currentQuantity': 'Current Quantity',
    'reconciliation.actualQuantity': 'Actual Quantity',
    'reconciliation.adjustment': 'Adjustment',
    'reconciliation.submit': 'Submit Reconciliation',
    'reconciliation.submitting': 'Submitting...',
    'reconciliation.submittedSuccessfully': 'Reconciliation submitted successfully',
    'reconciliation.submitError': 'Error submitting reconciliation',
    'reconciliation.accessDenied': 'Access Denied',
    'reconciliation.adminOnly': 'This page is only available to administrators',
    'reconciliation.noItems': 'No items found for reconciliation',
    'reconciliation.noAdjustments': 'No adjustments to submit',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.products': 'Produits',
    'nav.categories': 'Catégories',
    'nav.suppliers': 'Fournisseurs',
    'nav.purchaseOrders': 'Commandes d\'achat',
    'nav.dispensations': 'Dispensations',
    'nav.medicationAvailability': 'Disponibilité Médicaments',
    'nav.currentStock': 'Stock Actuel',
    'nav.dispensationTracking': 'Suivi Dispensations',
    'nav.inventory': 'Inventaire',
    'nav.reports': 'Rapports',
    'nav.users': 'Utilisateurs',
    'nav.reconciliation': 'Réconciliation',
    
    // Common
    'common.welcome': 'Bienvenue',
    'common.signOut': 'Se déconnecter',
    'common.language': 'Langue',
    'common.english': 'English',
    'common.french': 'Français',
    'common.units': 'unités',
    
    // App title
    'app.title': 'Gestion de Pharmacie Hospitalière',
    
    // Dashboard
    'dashboard.subtitle': 'Vue d\'ensemble de l\'inventaire pharmaceutique',
    'dashboard.recentMovements': 'Mouvements récents',
    'dashboard.recentMovementsSubtitle': 'Derniers mouvements d\'inventaire',
    'dashboard.loading': 'Chargement...',
    'dashboard.totalItems': 'Articles totaux',
    'dashboard.totalItemsDesc': 'Inventaire actif',
    'dashboard.totalStock': 'Stock total',
    'dashboard.totalStockDesc': 'Unités en stock',
    'dashboard.recentMovementsTitle': 'Mouvements récents',
    'dashboard.recentMovementsDesc': '10 derniers mouvements',
    
    // Inventory
    'inventory.subtitle': 'Vue d\'ensemble des mouvements d\'inventaire',
    'inventory.loading': 'Chargement...',
    'inventory.error': 'Erreur lors du chargement des données d\'inventaire',
    'inventory.totalItems': 'Articles totaux',
    'inventory.totalStock': 'Stock total',
    'inventory.recentMovements': 'Mouvements récents',
    'inventory.search': 'Rechercher',
    'inventory.searchPlaceholder': 'Nom de l\'article...',
    'inventory.movementType': 'Type de mouvement',
    'inventory.allTypes': 'Tous les types',
    'inventory.startDate': 'Date de début',
    'inventory.endDate': 'Date de fin',
    'inventory.date': 'Date',
    'inventory.item': 'Article',
    'inventory.type': 'Type',
    'inventory.quantity': 'Quantité',
    'inventory.user': 'Utilisateur',
    'inventory.notes': 'Notes',
    'inventory.noMovements': 'Aucun mouvement d\'inventaire trouvé avec les critères sélectionnés',
    'inventory.purchase': 'Achat',
    'inventory.dispensation': 'Dispensation',
    'inventory.adjustment': 'Ajustement',
    'inventory.transfer': 'Transfert',
    'inventory.expired': 'Expiré',
    'inventory.damaged': 'Endommagé',
    'inventory.return': 'Retour',
    'inventory.currentStock': 'Stock actuel',
    'inventory.stockLevel': 'Niveau de stock',
    'inventory.form': 'Forme',
    'inventory.expiryDate': 'Date d\'expiration',
    'inventory.description': 'Description',
    'inventory.noStock': 'Aucun article en stock trouvé',
    'inventory.lowStock': 'Stock faible',
    'inventory.outOfStock': 'Rupture de stock',
    'inventory.inStock': 'En stock',
    'inventory.sortBy': 'Trier par',
    'inventory.sortOrder': 'Ordre de tri',
    'inventory.ascending': 'Croissant',
    'inventory.descending': 'Décroissant',
    'inventory.form.capsule': 'Gélule',
    'inventory.form.tablet': 'Comprimé',
    'inventory.form.eyeDrops': 'Collyre',
    'inventory.form.cream': 'Pommade',
    'inventory.form.gel': 'Gel',
    'inventory.form.powder': 'Poudre',
    
    // Item Modal
    'inventory.modal.addNewItem': 'Ajouter un Nouvel Article',
    'inventory.modal.editItem': 'Modifier l\'Article',
    'inventory.modal.name': 'Nom',
    'inventory.modal.nameRequired': 'Nom *',
    'inventory.modal.description': 'Description',
    'inventory.modal.form': 'Forme',
    'inventory.modal.expiryDate': 'Date d\'Expiration (MM-YYYY)',
    'inventory.modal.expiryDatePlaceholder': 'MM-YYYY',
    'inventory.modal.currentStock': 'Stock Actuel',
    'inventory.modal.initialStock': 'Stock Initial',
    'inventory.modal.initialQuantity': 'Quantité Initiale',
    'inventory.modal.quantityHint': 'Définir la quantité initiale pour cet article',
    'inventory.modal.actions': 'Actions',
    'inventory.modal.cancel': 'Annuler',
    'inventory.modal.create': 'Créer',
    'inventory.modal.update': 'Mettre à jour',
    'inventory.modal.saving': 'Enregistrement...',
    'inventory.modal.adjustHint': 'Pour ajuster les quantités de stock, veuillez utiliser la fonction de réconciliation.',
    
    // Dispensation
    'dispensation.subtitle': 'Historique des mouvements d\'inventaire et dispensations',
    'dispensation.loading': 'Chargement...',
    'dispensation.error': 'Erreur lors du chargement des données de dispensation',
    'dispensation.purchases': 'Achats',
    'dispensation.dispensations': 'Dispensations',
    'dispensation.adjustments': 'Ajustements',
    'dispensation.losses': 'Pertes',
    'dispensation.search': 'Rechercher',
    'dispensation.searchPlaceholder': 'Nom de l\'article...',
    'dispensation.movementType': 'Type de mouvement',
    'dispensation.allTypes': 'Tous les types',
    'dispensation.dateFrom': 'Date de début',
    'dispensation.dateTo': 'Date de fin',
    'dispensation.date': 'Date',
    'dispensation.item': 'Article',
    'dispensation.type': 'Type',
    'dispensation.quantity': 'Quantité',
    'dispensation.user': 'Utilisateur',
    'dispensation.notes': 'Notes',
    'dispensation.noMovements': 'Aucun mouvement de dispensation trouvé avec les critères sélectionnés',
    'dispensation.purchase': 'Achat',
    'dispensation.dispensation': 'Dispensation',
    'dispensation.adjustment': 'Ajustement',
    'dispensation.transfer': 'Transfert',
    'dispensation.expired': 'Expiré',
    'dispensation.damaged': 'Endommagé',
    'dispensation.return': 'Retour',
    
    // Dispensations
    'dispensations.subtitle': 'Enregistrer les dispensations de médicaments rapidement et efficacement',
    'dispensations.loading': 'Chargement...',
    'dispensations.error': 'Erreur lors du chargement des données de dispensation',
    'dispensations.recentPrescriptions': 'Médicaments Prescrits Récents',
    'dispensations.searchPlaceholder': 'Rechercher des médicaments...',
    'dispensations.selectMedication': 'Sélectionner un Médicament à Dispenser',
    'dispensations.forms': 'formes',
    'dispensations.noMedications': 'Aucun médicament disponible pour la dispensation',
    'dispensations.dispenseMedication': 'Dispenser le Médicament',
    'dispensations.form': 'Forme',
    'dispensations.selectForm': 'Sélectionner la Forme',
    'dispensations.expiryDate': 'Date d\'Expiration',
    'dispensations.selectExpiry': 'Sélectionner la Date d\'Expiration',
    'dispensations.quantity': 'Quantité',
    'dispensations.notes': 'Notes',
    'dispensations.notesPlaceholder': 'Notes supplémentaires (optionnel)',
    'dispensations.dispense': 'Ajouter à la Mise en Scène',
    'dispensations.dispensedSuccessfully': 'Médicaments dispensés avec succès',
    'dispensations.errorDispensing': 'Erreur lors de la dispensation des médicaments',
    'dispensations.stagingArea': 'Zone de Mise en Scène',
    'dispensations.stagingSubtitle': 'Examiner les médicaments avant la dispensation',
    'dispensations.noStagedItems': 'Aucun médicament mis en scène',
    'dispensations.totalItems': 'Articles Totaux',
    'dispensations.totalQuantity': 'Quantité Totale',
    'dispensations.confirmDispensation': 'Confirmer la Dispensation',
    'dispensations.noStagedMedications': 'Aucun médicament mis en scène pour la dispensation',
    'dispensations.noExpiryDatesForForm': 'Aucune date d\'expiration disponible pour cette forme',
    'dispensations.clickToDispense': 'Cliquer pour dispenser',
    
    // Common
    'common.optional': 'Optionnel',
    'common.cancel': 'Annuler',
    'common.saving': 'Enregistrement...',
    
    // Users
    'users.subtitle': 'Gérer les comptes utilisateurs et les permissions',
    'users.comingSoon': 'Gestion des utilisateurs bientôt disponible...',
    'users.loading': 'Chargement des utilisateurs...',
    'users.error': 'Erreur lors du chargement des utilisateurs',
    'users.addUser': 'Ajouter un utilisateur',
    'users.editUser': 'Modifier l\'utilisateur',
    'users.deleteUser': 'Supprimer l\'utilisateur',
    'users.username': 'Nom d\'utilisateur',
    'users.password': 'Mot de passe',
    'users.firstName': 'Prénom',
    'users.lastName': 'Nom de famille',
    'users.role': 'Rôle',
    'users.status': 'Statut',
    'users.actions': 'Actions',
    'users.save': 'Enregistrer',
    'users.cancel': 'Annuler',
    'users.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ?',
    'users.userDeleted': 'Utilisateur supprimé avec succès',
    'users.userUpdated': 'Utilisateur mis à jour avec succès',
    'users.userCreated': 'Utilisateur créé avec succès',
    'users.errorUpdating': 'Erreur lors de la mise à jour de l\'utilisateur',
    'users.errorCreating': 'Erreur lors de la création de l\'utilisateur',
    'users.errorDeleting': 'Erreur lors de la suppression de l\'utilisateur',
    'users.roleAdmin': 'Administrateur',
    'users.rolePharmacist': 'Pharmacien',
    'users.roleTechnician': 'Technicien',
    'users.statusActive': 'Actif',
    'users.statusInactive': 'Inactif',
    'users.newPassword': 'Nouveau mot de passe',
    'users.confirmPassword': 'Confirmer le mot de passe',
    'users.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'users.passwordRequired': 'Le mot de passe est requis',
    'users.passwordMinLength': 'Le mot de passe doit contenir au moins 6 caractères',
    'users.usernameRequired': 'Le nom d\'utilisateur est requis',
    'users.firstNameRequired': 'Le prénom est requis',
    'users.lastNameRequired': 'Le nom de famille est requis',
    'users.roleRequired': 'Le rôle est requis',
    'users.accessDenied': 'Accès refusé',
    'users.noPermission': 'Vous n\'avez pas la permission d\'accéder à cette page.',
    'users.userCreatedSuccess': 'Utilisateur créé avec succès',
    'users.userUpdatedSuccess': 'Utilisateur mis à jour avec succès',
    'users.userDeletedSuccess': 'Utilisateur supprimé avec succès',
    'users.createError': 'Erreur lors de la création de l\'utilisateur',
    'users.updateError': 'Erreur lors de la mise à jour de l\'utilisateur',
    'users.deleteError': 'Erreur lors de la suppression de l\'utilisateur',
    'users.saving': 'Enregistrement...',
    'users.deleting': 'Suppression...',
    'users.success': 'Succès',
    'users.dismiss': 'Fermer',
    'users.search': 'Rechercher',
    'users.searchPlaceholder': 'Rechercher par nom ou nom d\'utilisateur...',
    'users.filterByRole': 'Filtrer par Rôle',
    'users.allRoles': 'Tous les Rôles',
    'users.clearFilters': 'Effacer les Filtres',
    'users.previous': 'Précédent',
    'users.next': 'Suivant',
    'users.showing': 'Affichage',
    'users.to': 'à',
    'users.of': 'sur',
    'users.results': 'résultats',
    
    // Login
    'login.title': 'Gestion de Pharmacie Hospitalière',
    'login.subtitle': 'Connectez-vous à votre compte',
    'login.username': 'Nom d\'utilisateur',
    'login.password': 'Mot de passe',
    'login.signIn': 'Se connecter',
    'login.signingIn': 'Connexion...',
    'login.credentials': 'Identifiants de connexion par défaut:',
    'login.usernameRequired': 'Le nom d\'utilisateur est requis',
    'login.usernameMinLength': 'Le nom d\'utilisateur doit contenir au moins 3 caractères',
    'login.passwordRequired': 'Le mot de passe est requis',
    'login.loginFailed': 'Échec de la connexion',
    'login.adminCredentials': 'Admin: admin / admin123',
    'login.pharmacistCredentials': 'Pharmacien: pharmacist / pharmacist123',
    'login.technicianCredentials': 'Technicien: tech / tech123',
    
    // Reconciliation
    'reconciliation.title': 'Réconciliation d\'Inventaire',
    'reconciliation.subtitle': 'Réconcilier les quantités réelles de médicaments avec les enregistrements du système',
    'reconciliation.totalItems': 'Articles Totaux',
    'reconciliation.totalCurrentStock': 'Stock Actuel Total',
    'reconciliation.totalActualStock': 'Stock Réel Total',
    'reconciliation.currentQuantity': 'Quantité Actuelle',
    'reconciliation.actualQuantity': 'Quantité Réelle',
    'reconciliation.adjustment': 'Ajustement',
    'reconciliation.submit': 'Soumettre la Réconciliation',
    'reconciliation.submitting': 'Soumission...',
    'reconciliation.submittedSuccessfully': 'Réconciliation soumise avec succès',
    'reconciliation.submitError': 'Erreur lors de la soumission de la réconciliation',
    'reconciliation.accessDenied': 'Accès Refusé',
    'reconciliation.adminOnly': 'Cette page n\'est disponible qu\'aux administrateurs',
    'reconciliation.noItems': 'Aucun article trouvé pour la réconciliation',
    'reconciliation.noAdjustments': 'Aucun ajustement à soumettre',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
